### ISSUE TITLE
Information about Test cases

### ISSUE THREAD

**Issue by Vishnu-2810** [Contrast-Security-OSS/vulnpy#130]
can i get the vulnerabilities count present in this web application for each framework like:
django : [vulnerability count]
flask : [vulnerability count]

... and so on
For each and every framework present in this web application if not aleast provide the overall count

**Comment by Vishnu-2810** [comment]
@nliccione can you please help me on this. 

Thanks in advance.

**Comment by lazorchakp** [comment]
A good way to check the number of vulnerabilities `vulnpy` provides is to check for unique function definitions starting with `do_*`. The `src/vulnpy/trigger/` directory contains all of these vulnerable function definitions.

To see these functions, you can clone the repo and grep for them:
```
grep 'def do_' src/vulnpy/trigger/*
```

With a little extra effort, here's a pipeline that generates nicer output:
```
grep -c 'def do_' src/vulnpy/trigger/* | grep -v :0 | sed 's|src/vulnpy/trigger/||g' | sed 's/\.py:/ /g'
```

So the current count, using the command above, is:
```
cmdi 2
deserialization 4
hash 3
parameter_pollution 1
pt 8
rand 4
redos 16
sqli 3
ssrf 13
unsafe_code_exec 3
xpath 3
xss 1
xxe 3
```

Please note that this is subject to change at any time.

**Comment by Vishnu-2810** [comment]
Thanks for your reply @lazorchakp
